-- ============================================================
-- v2_create_purchase_batch: atomic RPC for purchase batch creation
-- Wraps batch + line items + product/SKU find-or-create + UID
-- reservation + stock_unit insert + cost apportionment in a single
-- transaction. Any failure => full rollback. No orphan batches.
-- ============================================================

CREATE OR REPLACE FUNCTION public.v2_create_purchase_batch(p_input jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_batch_id text;
  v_supplier_name text;
  v_purchase_date date;
  v_reference text;
  v_supplier_vat boolean;
  v_shared_costs jsonb;
  v_total_shared numeric;
  v_line_items jsonb;
  v_line jsonb;
  v_line_id uuid;
  v_total_units int := 0;
  v_unique_mpns text[];
  v_mpn text;
  v_product_id uuid;
  v_sku_id uuid;
  v_sku_id_by_mpn jsonb := '{}'::jsonb;
  v_uids text[];
  v_uid_cursor int := 1;
  v_unit_inserts jsonb := '[]'::jsonb;
  v_qty int;
  v_unit_cost numeric;
  v_audit_id uuid;
  v_actor uuid := auth.uid();
  v_result jsonb;
BEGIN
  -- ── Authorization ─────────────────────────────────────────
  IF NOT (
    public.has_role(v_actor, 'admin'::app_role)
    OR public.has_role(v_actor, 'staff'::app_role)
  ) THEN
    RAISE EXCEPTION 'Forbidden: admin or staff role required'
      USING ERRCODE = '42501';
  END IF;

  -- ── Extract & validate input ──────────────────────────────
  v_supplier_name := trim(p_input->>'supplier_name');
  IF v_supplier_name IS NULL OR v_supplier_name = '' THEN
    RAISE EXCEPTION 'supplier_name is required';
  END IF;

  v_purchase_date := COALESCE((p_input->>'purchase_date')::date, CURRENT_DATE);
  v_reference := NULLIF(trim(p_input->>'reference'), '');
  v_supplier_vat := COALESCE((p_input->>'supplier_vat_registered')::boolean, false);
  v_shared_costs := COALESCE(p_input->'shared_costs', '{}'::jsonb);
  v_total_shared :=
    COALESCE((v_shared_costs->>'shipping')::numeric, 0)
    + COALESCE((v_shared_costs->>'broker_fee')::numeric, 0)
    + COALESCE((v_shared_costs->>'other')::numeric, 0);

  v_line_items := p_input->'line_items';
  IF v_line_items IS NULL OR jsonb_array_length(v_line_items) = 0 THEN
    RAISE EXCEPTION 'At least one line item is required';
  END IF;

  -- Validate every line item up-front so we fail before any insert
  FOR v_line IN SELECT jsonb_array_elements(v_line_items) LOOP
    IF NULLIF(trim(v_line->>'mpn'), '') IS NULL THEN
      RAISE EXCEPTION 'Line item mpn is required';
    END IF;
    v_qty := (v_line->>'quantity')::int;
    v_unit_cost := (v_line->>'unit_cost')::numeric;
    IF v_qty IS NULL OR v_qty < 1 THEN
      RAISE EXCEPTION 'Line item % has invalid quantity', v_line->>'mpn';
    END IF;
    IF v_unit_cost IS NULL OR v_unit_cost < 0 THEN
      RAISE EXCEPTION 'Line item % has invalid unit_cost', v_line->>'mpn';
    END IF;
    v_total_units := v_total_units + v_qty;
  END LOOP;

  -- ── 1. Insert batch header (id auto-generated by sequence) ─
  INSERT INTO public.purchase_batches (
    supplier_name, purchase_date, reference,
    supplier_vat_registered, shared_costs, total_shared_costs, status
  ) VALUES (
    v_supplier_name, v_purchase_date, v_reference,
    v_supplier_vat, v_shared_costs, v_total_shared, 'draft'
  )
  RETURNING id INTO v_batch_id;

  -- ── 2. Find-or-create product + grade-5 placeholder SKU per MPN
  SELECT array_agg(DISTINCT trim(elem->>'mpn'))
  INTO v_unique_mpns
  FROM jsonb_array_elements(v_line_items) elem;

  FOREACH v_mpn IN ARRAY v_unique_mpns LOOP
    -- Product
    INSERT INTO public.product (mpn, name, set_number)
    VALUES (
      v_mpn,
      v_mpn,
      CASE WHEN v_mpn ~ '^\d+-\d+$' THEN split_part(v_mpn, '-', 1) ELSE NULL END
    )
    ON CONFLICT (mpn) DO UPDATE SET mpn = EXCLUDED.mpn  -- no-op to force RETURNING
    RETURNING id INTO v_product_id;

    -- Placeholder grade-5 SKU
    INSERT INTO public.sku (
      sku_code, product_id, mpn, condition_grade,
      active_flag, saleable_flag, name
    )
    VALUES (
      v_mpn || '.5', v_product_id, v_mpn, '5'::condition_grade,
      true, false, v_mpn
    )
    ON CONFLICT (sku_code) DO UPDATE SET sku_code = EXCLUDED.sku_code  -- no-op to force RETURNING
    RETURNING id INTO v_sku_id;

    v_sku_id_by_mpn := v_sku_id_by_mpn || jsonb_build_object(v_mpn, v_sku_id::text);
  END LOOP;

  -- ── 3. Insert line items, capturing returned ids ──────────
  CREATE TEMP TABLE _new_lines (
    id uuid,
    mpn text,
    quantity int,
    unit_cost numeric
  ) ON COMMIT DROP;

  WITH inserted AS (
    INSERT INTO public.purchase_line_items (batch_id, mpn, quantity, unit_cost)
    SELECT v_batch_id,
           trim(elem->>'mpn'),
           (elem->>'quantity')::int,
           (elem->>'unit_cost')::numeric
    FROM jsonb_array_elements(v_line_items) elem
    RETURNING id, mpn, quantity, unit_cost
  )
  INSERT INTO _new_lines SELECT * FROM inserted;

  -- ── 4. Reserve UIDs atomically ────────────────────────────
  IF v_total_units > 0 THEN
    v_uids := public.v2_reserve_stock_unit_uids(v_batch_id, v_total_units);
    IF array_length(v_uids, 1) IS DISTINCT FROM v_total_units THEN
      RAISE EXCEPTION 'UID reservation returned % uids, expected %',
        COALESCE(array_length(v_uids, 1), 0), v_total_units;
    END IF;
  END IF;

  -- ── 5. Bulk insert stock_units ────────────────────────────
  INSERT INTO public.stock_unit (
    uid, sku_id, mpn, condition_grade,
    batch_id, line_item_id, landed_cost,
    v2_status, status
  )
  SELECT
    v_uids[seq.unit_index],
    (v_sku_id_by_mpn->>l.mpn)::uuid,
    l.mpn,
    '5'::condition_grade,
    v_batch_id,
    l.id,
    l.unit_cost,
    'purchased',
    'pending_receipt'::stock_unit_status
  FROM (
    SELECT id, mpn, quantity, unit_cost,
           SUM(quantity) OVER (ORDER BY id) - quantity AS prev_total
    FROM _new_lines
  ) l
  CROSS JOIN LATERAL generate_series(1, l.quantity) AS gs(n)
  CROSS JOIN LATERAL (SELECT (l.prev_total + gs.n)::int AS unit_index) seq;

  -- ── 6. Apportion costs ────────────────────────────────────
  PERFORM public.v2_calculate_apportioned_costs(v_batch_id);

  -- ── 7. Audit success ──────────────────────────────────────
  v_result := jsonb_build_object(
    'batch_id', v_batch_id,
    'line_item_count', jsonb_array_length(v_line_items),
    'unit_count', v_total_units
  );

  INSERT INTO public.audit_event (
    entity_type, entity_id, trigger_type, actor_type, actor_id,
    source_system, input_json, output_json
  )
  VALUES (
    'purchase_batch',
    gen_random_uuid(),  -- entity_id is uuid; batch_id is text, store in output
    'purchase_batch_create',
    'user',
    v_actor,
    'admin_v2',
    p_input,
    v_result
  );

  RETURN v_result;
EXCEPTION WHEN OTHERS THEN
  -- Audit the failure (separate connection-safe write since txn will roll back)
  -- We can't write here because the surrounding txn is being rolled back.
  -- Instead, raise with full context so the client logs it; nightly drift
  -- check will catch any anomalies.
  RAISE;
END;
$$;

GRANT EXECUTE ON FUNCTION public.v2_create_purchase_batch(jsonb) TO authenticated;

-- ============================================================
-- Nightly drift check: detect orphan draft batches
-- ============================================================

CREATE OR REPLACE FUNCTION public.v2_detect_orphan_purchase_batches()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_row record;
  v_count int := 0;
BEGIN
  FOR v_row IN
    SELECT pb.id, pb.created_at, pb.supplier_name, pb.unit_counter,
           (SELECT count(*) FROM public.purchase_line_items WHERE batch_id = pb.id) AS line_count,
           (SELECT count(*) FROM public.stock_unit WHERE batch_id = pb.id) AS unit_count
    FROM public.purchase_batches pb
    WHERE pb.status = 'draft'
      AND pb.created_at < now() - interval '15 minutes'
      AND pb.unit_counter = 0
      -- Avoid re-flagging
      AND NOT EXISTS (
        SELECT 1 FROM public.audit_event ae
        WHERE ae.trigger_type = 'purchase_batch_orphan_detected'
          AND ae.output_json->>'batch_id' = pb.id
      )
  LOOP
    INSERT INTO public.audit_event (
      entity_type, entity_id, trigger_type, actor_type,
      source_system, output_json
    ) VALUES (
      'purchase_batch',
      gen_random_uuid(),
      'purchase_batch_orphan_detected',
      'system',
      'cron',
      jsonb_build_object(
        'batch_id', v_row.id,
        'created_at', v_row.created_at,
        'supplier_name', v_row.supplier_name,
        'line_count', v_row.line_count,
        'unit_count', v_row.unit_count
      )
    );
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$;

-- Schedule nightly at 02:15 UTC
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('v2-detect-orphan-purchase-batches')
    WHERE EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = 'v2-detect-orphan-purchase-batches'
    );
    PERFORM cron.schedule(
      'v2-detect-orphan-purchase-batches',
      '15 2 * * *',
      $cron$SELECT public.v2_detect_orphan_purchase_batches();$cron$
    );
  END IF;
END $$;