-- Lovable catch-up migration for commerce subledger functions that were missed by earlier partial runs.
-- Generated by concatenating the Lovable-safe source migrations below.
-- Safe to re-run: all functions use CREATE OR REPLACE and supporting indexes use IF NOT EXISTS.


-- ============================================================
-- Source: supabase/migrations/20260430203000_queue_qbo_refund_posting_intents.sql
-- ============================================================

-- Queue QBO RefundReceipt posting intents for returned/refunded order lines.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies, not dollar-quoted delimiters.

CREATE OR REPLACE FUNCTION public.queue_qbo_refund_posting_intent_for_order(
  p_sales_order_id UUID,
  p_refunded_line_ids UUID[] DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_order public.sales_order%ROWTYPE;
  v_line_ids UUID[];
  v_intent_id UUID;
  v_idempotency_key TEXT;
BEGIN
  SELECT * INTO v_order
  FROM public.sales_order
  WHERE id = p_sales_order_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''sales_order % not found'', p_sales_order_id;
  END IF;

  SELECT COALESCE(array_agg(line_id ORDER BY line_id), ARRAY[]::uuid[])
  INTO v_line_ids
  FROM (
    SELECT DISTINCT unnest(COALESCE(p_refunded_line_ids, ARRAY[]::uuid[])) AS line_id
  ) lines
  WHERE line_id IS NOT NULL;

  IF array_length(v_line_ids, 1) IS NULL THEN
    SELECT COALESCE(array_agg(sol.id ORDER BY sol.id), ARRAY[]::uuid[])
    INTO v_line_ids
    FROM public.sales_order_line sol
    JOIN public.stock_unit su ON su.id = sol.stock_unit_id
    WHERE sol.sales_order_id = p_sales_order_id
      AND su.v2_status = ''refunded'';
  END IF;

  IF array_length(v_line_ids, 1) IS NULL THEN
    RAISE EXCEPTION ''No refunded sales_order_line rows found for order %'', p_sales_order_id;
  END IF;

  v_idempotency_key :=
    ''qbo_refund_receipt:'' || p_sales_order_id::text || '':'' || array_to_string(v_line_ids, '','');

  INSERT INTO public.posting_intent (
    target_system,
    action,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    ''qbo'',
    ''create_refund_receipt'',
    ''sales_order'',
    p_sales_order_id,
    v_idempotency_key,
    ''pending'',
    jsonb_build_object(
      ''sales_order_id'', p_sales_order_id,
      ''refunded_line_ids'', to_jsonb(v_line_ids),
      ''source'', ''return_processor''
    )
  )
  ON CONFLICT (target_system, action, idempotency_key) DO UPDATE
  SET status = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'') THEN ''pending''
        ELSE posting_intent.status
      END,
      next_attempt_at = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'') THEN now()
        ELSE posting_intent.next_attempt_at
      END,
      payload = EXCLUDED.payload,
      updated_at = now()
  RETURNING id INTO v_intent_id;

  RETURN v_intent_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_qbo_refund_posting_intent_for_order(UUID, UUID[])
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430210000_enhance_reconciliation_case_rebuild.sql
-- ============================================================

-- Expand reconciliation case generation to cover the exception types in the
-- commerce subledger plan. Lovable SQL runner note: single-quoted PL/pgSQL only.

CREATE INDEX IF NOT EXISTS idx_reconciliation_case_open_type_order
  ON public.reconciliation_case(case_type, sales_order_id, status)
  WHERE status IN ('open', 'in_progress');

CREATE INDEX IF NOT EXISTS idx_reconciliation_case_open_related
  ON public.reconciliation_case(case_type, related_entity_type, related_entity_id, status)
  WHERE status IN ('open', 'in_progress');

CREATE INDEX IF NOT EXISTS idx_payout_fee_unmatched
  ON public.payout_fee(created_at, external_order_id)
  WHERE sales_order_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_posting_intent_qbo_failed
  ON public.posting_intent(entity_type, entity_id, created_at)
  WHERE target_system = 'qbo' AND status = 'failed';

CREATE OR REPLACE FUNCTION public.rebuild_reconciliation_cases(p_sales_order_id UUID DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_count INTEGER := 0;
  v_inserted INTEGER := 0;
BEGIN
  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    sales_order_line_id,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    evidence
  )
  SELECT
    ''unallocated_order_line'',
    ''high'',
    sol.sales_order_id,
    sol.id,
    ''sales_order_line'',
    sol.id,
    ''Sale line has not been allocated to a stock unit.'',
    ''Allocate stock through the costing subledger or approve a manual allocation exception.'',
    jsonb_build_object(
      ''sku_id'', sol.sku_id,
      ''quantity'', sol.quantity,
      ''economics_status'', sol.economics_status
    )
  FROM public.sales_order_line sol
  WHERE (p_sales_order_id IS NULL OR sol.sales_order_id = p_sales_order_id)
    AND sol.stock_unit_id IS NULL
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''unallocated_order_line''
        AND rc.sales_order_line_id = sol.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    sales_order_line_id,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    evidence
  )
  SELECT
    ''missing_cogs'',
    ''high'',
    sol.sales_order_id,
    sol.id,
    ''sales_order_line'',
    sol.id,
    ''Sale line has no finalized COGS.'',
    ''Allocate stock or approve a manual costing exception before final accounting close.'',
    jsonb_build_object(
      ''sku_id'', sol.sku_id,
      ''stock_unit_id'', sol.stock_unit_id,
      ''costing_method'', sol.costing_method,
      ''economics_status'', sol.economics_status
    )
  FROM public.sales_order_line sol
  WHERE (p_sales_order_id IS NULL OR sol.sales_order_id = p_sales_order_id)
    AND sol.stock_unit_id IS NOT NULL
    AND (
      sol.cogs_amount IS NULL
      OR sol.cogs_amount = 0
      OR sol.economics_status IN (''needs_allocation'', ''incomplete'')
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''missing_cogs''
        AND rc.sales_order_line_id = sol.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    amount_expected,
    evidence
  )
  SELECT
    ''unmatched_payout_fee'',
    ''medium'',
    ''payout_fee'',
    pf.id,
    ''Payout fee has no matched local sales order.'',
    ''Late-match by external order ID or classify it as a platform-level fee allocation.'',
    pf.amount,
    jsonb_build_object(
      ''payout_id'', pf.payout_id,
      ''external_order_id'', pf.external_order_id,
      ''channel'', pf.channel,
      ''fee_category'', pf.fee_category
    )
  FROM public.payout_fee pf
  WHERE p_sales_order_id IS NULL
    AND pf.sales_order_id IS NULL
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''unmatched_payout_fee''
        AND rc.related_entity_type = ''payout_fee''
        AND rc.related_entity_id = pf.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    suspected_root_cause,
    recommended_action,
    amount_expected,
    amount_actual,
    variance_amount,
    evidence
  )
  WITH expected AS (
    SELECT sales_order_id, ROUND(SUM(amount), 2) AS expected_amount
    FROM public.expected_settlement_line
    WHERE sales_order_id IS NOT NULL
      AND (p_sales_order_id IS NULL OR sales_order_id = p_sales_order_id)
    GROUP BY sales_order_id
  ),
  actual AS (
    SELECT sales_order_id, ROUND(SUM(amount), 2) AS actual_amount
    FROM public.actual_settlement_line
    WHERE sales_order_id IS NOT NULL
      AND (p_sales_order_id IS NULL OR sales_order_id = p_sales_order_id)
    GROUP BY sales_order_id
  )
  SELECT
    ''amount_mismatch'',
    CASE WHEN ABS(e.expected_amount - COALESCE(a.actual_amount, 0)) > 5 THEN ''high'' ELSE ''medium'' END,
    e.sales_order_id,
    ''Expected and actual settlement amounts differ outside tolerance.'',
    ''Review payout, fee, refund, and QBO posting evidence.'',
    e.expected_amount,
    COALESCE(a.actual_amount, 0),
    e.expected_amount - COALESCE(a.actual_amount, 0),
    jsonb_build_object(''expected'', e.expected_amount, ''actual'', COALESCE(a.actual_amount, 0))
  FROM expected e
  LEFT JOIN actual a ON a.sales_order_id = e.sales_order_id
  WHERE ABS(e.expected_amount - COALESCE(a.actual_amount, 0)) > 0.05
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''amount_mismatch''
        AND rc.sales_order_id = e.sales_order_id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    suspected_root_cause,
    recommended_action,
    amount_expected,
    amount_actual,
    variance_amount,
    due_at,
    evidence
  )
  WITH expected AS (
    SELECT esl.sales_order_id, ROUND(SUM(esl.amount), 2) AS expected_amount
    FROM public.expected_settlement_line esl
    JOIN public.sales_order so ON so.id = esl.sales_order_id
    WHERE (p_sales_order_id IS NULL OR esl.sales_order_id = p_sales_order_id)
      AND so.created_at < now() - interval ''7 days''
      AND COALESCE(so.origin_channel, '''') NOT IN (''in_person'', ''cash'', ''qbo'', ''qbo_refund'')
    GROUP BY esl.sales_order_id
  )
  SELECT
    ''missing_payout'',
    ''medium'',
    e.sales_order_id,
    ''No actual settlement evidence has been linked beyond the payout SLA.'',
    ''Import or reconcile the channel payout, then refresh settlement lines.'',
    e.expected_amount,
    0,
    e.expected_amount,
    so.created_at + interval ''7 days'',
    jsonb_build_object(
      ''origin_channel'', so.origin_channel,
      ''order_number'', so.order_number,
      ''order_created_at'', so.created_at
    )
  FROM expected e
  JOIN public.sales_order so ON so.id = e.sales_order_id
  WHERE NOT EXISTS (
      SELECT 1
      FROM public.actual_settlement_line asl
      WHERE asl.sales_order_id = e.sales_order_id
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''missing_payout''
        AND rc.sales_order_id = e.sales_order_id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    amount_expected,
    evidence
  )
  SELECT
    ''unpaid_program_accrual'',
    ''medium'',
    spa.sales_order_id,
    ''sales_program_accrual'',
    spa.id,
    ''Program commission accrual is open and not attached to a settlement.'',
    ''Include this accrual in the next sales-program settlement run.'',
    spa.commission_amount - spa.reversed_amount,
    jsonb_build_object(
      ''sales_program_id'', spa.sales_program_id,
      ''status'', spa.status,
      ''currency'', spa.currency
    )
  FROM public.sales_program_accrual spa
  WHERE (p_sales_order_id IS NULL OR spa.sales_order_id = p_sales_order_id)
    AND spa.status IN (''open'', ''partially_settled'')
    AND spa.settlement_id IS NULL
    AND spa.commission_amount - spa.reversed_amount > 0
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''unpaid_program_accrual''
        AND rc.related_entity_type = ''sales_program_accrual''
        AND rc.related_entity_id = spa.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    evidence
  )
  SELECT
    ''qbo_posting_gap'',
    ''high'',
    pi.entity_id,
    ''posting_intent'',
    pi.id,
    ''QBO posting intent failed.'',
    ''Review the posting error, fix the source data or QBO mapping, then retry the outbox processor.'',
    jsonb_build_object(
      ''action'', pi.action,
      ''retry_count'', pi.retry_count,
      ''last_error'', pi.last_error,
      ''idempotency_key'', pi.idempotency_key
    )
  FROM public.posting_intent pi
  WHERE pi.target_system = ''qbo''
    AND pi.status = ''failed''
    AND pi.entity_type = ''sales_order''
    AND (p_sales_order_id IS NULL OR pi.entity_id = p_sales_order_id)
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''qbo_posting_gap''
        AND rc.related_entity_type = ''posting_intent''
        AND rc.related_entity_id = pi.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    sales_order_id,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    due_at,
    evidence
  )
  SELECT
    ''qbo_posting_gap'',
    ''medium'',
    so.id,
    ''sales_order'',
    so.id,
    ''Order has app-side accounting events but no QBO posting intent or posting reference.'',
    ''Queue QBO posting intents for the order, or mark the order as intentionally excluded with evidence.'',
    so.created_at + interval ''1 day'',
    jsonb_build_object(
      ''order_number'', so.order_number,
      ''origin_channel'', so.origin_channel,
      ''accounting_event_count'', COUNT(ae.id)
    )
  FROM public.sales_order so
  JOIN public.accounting_event ae ON ae.sales_order_id = so.id
  WHERE (p_sales_order_id IS NULL OR so.id = p_sales_order_id)
    AND so.created_at < now() - interval ''1 day''
    AND COALESCE(so.origin_channel, '''') NOT IN (''qbo'', ''qbo_refund'')
    AND NOT EXISTS (
      SELECT 1
      FROM public.posting_intent pi
      WHERE pi.target_system = ''qbo''
        AND pi.entity_type = ''sales_order''
        AND pi.entity_id = so.id
        AND pi.status IN (''pending'', ''processing'', ''posted'', ''failed'')
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.qbo_posting_reference qpr
      WHERE qpr.local_entity_type = ''sales_order''
        AND qpr.local_entity_id = so.id
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''qbo_posting_gap''
        AND rc.sales_order_id = so.id
        AND rc.related_entity_type = ''sales_order''
        AND rc.status IN (''open'', ''in_progress'')
    )
  GROUP BY so.id, so.order_number, so.origin_channel, so.created_at;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    related_entity_type,
    suspected_root_cause,
    recommended_action,
    amount_actual,
    evidence
  )
  WITH duplicates AS (
    SELECT
      source_system,
      external_reference,
      category,
      ROUND(SUM(amount), 2) AS total_amount,
      COUNT(*) AS duplicate_count,
      MIN(created_at) AS first_seen
    FROM public.actual_settlement_line
    WHERE p_sales_order_id IS NULL
      AND external_reference IS NOT NULL
    GROUP BY source_system, external_reference, category
    HAVING COUNT(*) > 1
  )
  SELECT
    ''duplicate_candidate'',
    ''medium'',
    ''actual_settlement_line'',
    ''Multiple actual settlement lines share the same external reference and category.'',
    ''Review payout import idempotency and remove or merge duplicate settlement evidence.'',
    d.total_amount,
    jsonb_build_object(
      ''source_system'', d.source_system,
      ''external_reference'', d.external_reference,
      ''category'', d.category,
      ''duplicate_count'', d.duplicate_count,
      ''first_seen'', d.first_seen
    )
  FROM duplicates d
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.reconciliation_case rc
    WHERE rc.case_type = ''duplicate_candidate''
      AND rc.related_entity_type = ''actual_settlement_line''
      AND rc.status IN (''open'', ''in_progress'')
      AND rc.evidence->>''source_system'' = d.source_system
      AND rc.evidence->>''external_reference'' = d.external_reference
      AND rc.evidence->>''category'' = d.category
  );

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  v_count := v_count + v_inserted;

  RETURN v_count;
END;
';

GRANT EXECUTE ON FUNCTION public.rebuild_reconciliation_cases(UUID)
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430213000_refresh_market_price_snapshots.sql
-- ============================================================

-- Build current market consensus snapshots from normalized market signals.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies only.

INSERT INTO public.market_signal_source (source_code, name, source_type, rate_limit_per_day, metadata)
VALUES (
  'market_consensus',
  'Weighted Market Consensus',
  'market_data',
  NULL,
  jsonb_build_object('generated_by', 'refresh_market_price_snapshots')
)
ON CONFLICT (source_code) DO UPDATE
SET name = EXCLUDED.name,
    source_type = EXCLUDED.source_type,
    metadata = public.market_signal_source.metadata || EXCLUDED.metadata,
    updated_at = now();

CREATE INDEX IF NOT EXISTS idx_market_signal_recent_price
  ON public.market_signal(sku_id, channel, observed_at DESC)
  WHERE sku_id IS NOT NULL AND observed_price IS NOT NULL AND observed_price > 0;

CREATE INDEX IF NOT EXISTS idx_market_price_snapshot_source_sku_channel
  ON public.market_price_snapshot(source_id, sku_id, channel, captured_at DESC)
  WHERE sku_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.refresh_market_price_snapshots(p_sku_id UUID DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_consensus_source_id UUID;
  v_internal_source_id UUID;
  v_count INTEGER := 0;
  v_rows INTEGER := 0;
BEGIN
  SELECT id INTO v_consensus_source_id
  FROM public.market_signal_source
  WHERE source_code = ''market_consensus'';

  SELECT id INTO v_internal_source_id
  FROM public.market_signal_source
  WHERE source_code = ''internal_realized_sale'';

  IF v_consensus_source_id IS NULL THEN
    RAISE EXCEPTION ''market_consensus source is missing'';
  END IF;

  IF v_internal_source_id IS NULL THEN
    RAISE EXCEPTION ''internal_realized_sale source is missing'';
  END IF;

  INSERT INTO public.market_signal (
    source_id,
    sku_id,
    mpn,
    condition_grade,
    channel,
    signal_type,
    observed_price,
    observed_price_min,
    observed_price_max,
    sample_size,
    vat_treatment,
    source_confidence,
    freshness_score,
    observed_at,
    metadata
  )
  SELECT
    v_internal_source_id,
    sol.sku_id,
    COALESCE(sk.mpn, p.mpn),
    sk.condition_grade,
    so.origin_channel,
    ''realized_margin'',
    ROUND((sol.line_total / NULLIF(sol.quantity, 0))::numeric, 2),
    ROUND((sol.line_total / NULLIF(sol.quantity, 0))::numeric, 2),
    ROUND((sol.line_total / NULLIF(sol.quantity, 0))::numeric, 2),
    GREATEST(sol.quantity, 1),
    ''inclusive'',
    0.85,
    GREATEST(0.10, LEAST(1.00, 1.00 - (EXTRACT(EPOCH FROM (now() - COALESCE(so.created_at, sol.created_at))) / 31536000.0)))::numeric,
    COALESCE(so.created_at, sol.created_at, now()),
    jsonb_build_object(
      ''sales_order_id'', sol.sales_order_id,
      ''sales_order_line_id'', sol.id,
      ''order_number'', so.order_number,
      ''origin_channel'', so.origin_channel
    )
  FROM public.sales_order_line sol
  JOIN public.sales_order so ON so.id = sol.sales_order_id
  JOIN public.sku sk ON sk.id = sol.sku_id
  LEFT JOIN public.product p ON p.id = sk.product_id
  WHERE (p_sku_id IS NULL OR sol.sku_id = p_sku_id)
    AND sol.quantity > 0
    AND sol.line_total > 0
    AND COALESCE(so.status::text, '''') NOT IN (''cancelled'', ''refunded'')
    AND NOT EXISTS (
      SELECT 1
      FROM public.market_signal ms
      WHERE ms.source_id = v_internal_source_id
        AND ms.metadata->>''sales_order_line_id'' = sol.id::text
    );

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  v_count := v_count + v_rows;

  INSERT INTO public.market_price_snapshot (
    source_id,
    sku_id,
    mpn,
    condition_grade,
    channel,
    price,
    price_low,
    price_high,
    currency,
    vat_treatment,
    sample_size,
    confidence_score,
    freshness_score,
    captured_at,
    metadata
  )
  WITH weighted_signals AS (
    SELECT
      ms.sku_id,
      COALESCE(ms.mpn, sk.mpn, p.mpn) AS mpn,
      COALESCE(ms.condition_grade, sk.condition_grade) AS condition_grade,
      COALESCE(NULLIF(ms.channel, ''''), ''all'') AS channel,
      ms.observed_price,
      COALESCE(ms.observed_price_min, ms.observed_price) AS observed_price_min,
      COALESCE(ms.observed_price_max, ms.observed_price) AS observed_price_max,
      COALESCE(ms.sample_size, 1) AS sample_size,
      ms.vat_treatment,
      GREATEST(0.05, LEAST(1.00, COALESCE(ms.source_confidence, 0.50))) AS confidence_part,
      GREATEST(
        0.05,
        LEAST(
          1.00,
          COALESCE(
            ms.freshness_score,
            1.00 - (EXTRACT(EPOCH FROM (now() - ms.observed_at)) / 31536000.0)
          )
        )
      ) AS freshness_part
    FROM public.market_signal ms
    LEFT JOIN public.sku sk ON sk.id = ms.sku_id
    LEFT JOIN public.product p ON p.id = sk.product_id
    JOIN public.market_signal_source mss ON mss.id = ms.source_id
    WHERE (p_sku_id IS NULL OR ms.sku_id = p_sku_id)
      AND ms.sku_id IS NOT NULL
      AND ms.observed_price IS NOT NULL
      AND ms.observed_price > 0
      AND ms.observed_at >= now() - interval ''365 days''
      AND mss.active = true
      AND mss.source_code <> ''market_consensus''
  ),
  scored AS (
    SELECT
      ws.*,
      (ws.confidence_part * ws.freshness_part * LEAST(5.00, SQRT(GREATEST(ws.sample_size, 1)))) AS signal_weight
    FROM weighted_signals ws
  ),
  grouped AS (
    SELECT
      sku_id,
      mpn,
      condition_grade,
      channel,
      ROUND((SUM(observed_price * signal_weight) / NULLIF(SUM(signal_weight), 0))::numeric, 2) AS price,
      ROUND(MIN(observed_price_min)::numeric, 2) AS price_low,
      ROUND(MAX(observed_price_max)::numeric, 2) AS price_high,
      SUM(sample_size)::integer AS sample_size,
      ROUND(AVG(confidence_part)::numeric, 6) AS confidence_score,
      ROUND(AVG(freshness_part)::numeric, 6) AS freshness_score,
      COUNT(*) AS signal_count,
      jsonb_agg(DISTINCT vat_treatment) AS vat_treatments
    FROM scored
    GROUP BY sku_id, mpn, condition_grade, channel
  ),
  all_channel AS (
    SELECT
      sku_id,
      mpn,
      condition_grade,
      ''all'' AS channel,
      ROUND((SUM(observed_price * signal_weight) / NULLIF(SUM(signal_weight), 0))::numeric, 2) AS price,
      ROUND(MIN(observed_price_min)::numeric, 2) AS price_low,
      ROUND(MAX(observed_price_max)::numeric, 2) AS price_high,
      SUM(sample_size)::integer AS sample_size,
      ROUND(AVG(confidence_part)::numeric, 6) AS confidence_score,
      ROUND(AVG(freshness_part)::numeric, 6) AS freshness_score,
      COUNT(*) AS signal_count,
      jsonb_agg(DISTINCT vat_treatment) AS vat_treatments
    FROM scored
    GROUP BY sku_id, mpn, condition_grade
  ),
  combined AS (
    SELECT * FROM grouped WHERE channel <> ''all''
    UNION ALL
    SELECT * FROM all_channel
  )
  SELECT
    v_consensus_source_id,
    c.sku_id,
    c.mpn,
    c.condition_grade,
    c.channel,
    c.price,
    c.price_low,
    c.price_high,
    ''GBP'',
    CASE
      WHEN c.vat_treatments ? ''inclusive'' THEN ''inclusive''
      WHEN c.vat_treatments ? ''exclusive'' THEN ''exclusive''
      ELSE ''unknown''
    END,
    c.sample_size,
    c.confidence_score,
    c.freshness_score,
    now(),
    jsonb_build_object(
      ''generated_by'', ''refresh_market_price_snapshots'',
      ''signal_count'', c.signal_count,
      ''source_window_days'', 365
    )
  FROM combined c
  WHERE c.price IS NOT NULL
    AND c.price > 0;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  v_count := v_count + v_rows;

  RETURN v_count;
END;
';

GRANT EXECUTE ON FUNCTION public.refresh_market_price_snapshots(UUID)
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430220000_listing_command_reconciliation_cases.sql
-- ============================================================

-- Surface failed listing outbox commands in the Operations reconciliation inbox.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies, not dollar quotes.

ALTER TABLE public.reconciliation_case
  DROP CONSTRAINT IF EXISTS reconciliation_case_case_type_check;

ALTER TABLE public.reconciliation_case
  ADD CONSTRAINT reconciliation_case_case_type_check
  CHECK (case_type IN (
    'missing_cogs',
    'unallocated_order_line',
    'unmatched_payout_fee',
    'missing_payout',
    'amount_mismatch',
    'unpaid_program_accrual',
    'qbo_posting_gap',
    'listing_command_failed',
    'duplicate_candidate',
    'other'
  )) NOT VALID;

CREATE INDEX IF NOT EXISTS idx_outbound_command_failed_listing
  ON public.outbound_command(entity_type, entity_id, created_at)
  WHERE entity_type = 'channel_listing' AND status = 'failed';

CREATE OR REPLACE FUNCTION public.rebuild_listing_command_reconciliation_cases()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_count INTEGER := 0;
BEGIN
  INSERT INTO public.reconciliation_case (
    case_type,
    severity,
    related_entity_type,
    related_entity_id,
    suspected_root_cause,
    recommended_action,
    due_at,
    evidence
  )
  SELECT
    ''listing_command_failed'',
    CASE
      WHEN oc.command_type IN (''publish'', ''end'') THEN ''high''
      ELSE ''medium''
    END,
    ''outbound_command'',
    oc.id,
    ''Listing outbound command failed.'',
    ''Review the listing command error, correct listing/channel data, then rerun the listing outbox processor.'',
    COALESCE(oc.next_attempt_at, oc.updated_at, oc.created_at),
    jsonb_build_object(
      ''target_system'', oc.target_system,
      ''command_type'', oc.command_type,
      ''entity_type'', oc.entity_type,
      ''entity_id'', oc.entity_id,
      ''retry_count'', oc.retry_count,
      ''last_error'', oc.last_error,
      ''idempotency_key'', oc.idempotency_key,
      ''payload'', oc.payload
    )
  FROM public.outbound_command oc
  WHERE oc.entity_type = ''channel_listing''
    AND oc.status = ''failed''
    AND NOT EXISTS (
      SELECT 1
      FROM public.reconciliation_case rc
      WHERE rc.case_type = ''listing_command_failed''
        AND rc.related_entity_type = ''outbound_command''
        AND rc.related_entity_id = oc.id
        AND rc.status IN (''open'', ''in_progress'')
    );

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
';

GRANT EXECUTE ON FUNCTION public.rebuild_listing_command_reconciliation_cases()
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430223000_listing_quantity_sync_outbox.sql
-- ============================================================

-- Route stock quantity synchronization through the listing outbox.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies, not dollar quotes.

CREATE OR REPLACE FUNCTION public.queue_listing_command(
  p_channel_listing_id UUID,
  p_command_type TEXT,
  p_actor_id UUID DEFAULT NULL,
  p_allow_below_floor BOOLEAN DEFAULT false
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_listing public.channel_listing%ROWTYPE;
  v_snapshot public.price_decision_snapshot%ROWTYPE;
  v_command_id UUID;
  v_target TEXT;
  v_available_quantity INTEGER := NULL;
  v_idempotency_key TEXT;
BEGIN
  SELECT * INTO v_listing
  FROM public.channel_listing
  WHERE id = p_channel_listing_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''channel_listing % not found'', p_channel_listing_id;
  END IF;

  IF p_command_type NOT IN (''publish'', ''reprice'', ''pause'', ''end'', ''update_price'', ''sync_quantity'') THEN
    RAISE EXCEPTION ''Unsupported listing command type %'', p_command_type;
  END IF;

  IF p_command_type <> ''sync_quantity''
     AND v_listing.current_price_decision_snapshot_id IS NULL
     AND v_listing.sku_id IS NOT NULL THEN
    PERFORM public.create_price_decision_snapshot(
      v_listing.sku_id,
      COALESCE(v_listing.channel, v_listing.v2_channel::text, ''website''),
      v_listing.id,
      v_listing.listed_price,
      NULL,
      p_actor_id
    );
  END IF;

  SELECT * INTO v_snapshot
  FROM public.price_decision_snapshot
  WHERE id = (
    SELECT current_price_decision_snapshot_id
    FROM public.channel_listing
    WHERE id = p_channel_listing_id
  );

  IF p_command_type IN (''publish'', ''reprice'', ''update_price'')
     AND COALESCE(v_snapshot.override_required, false)
     AND NOT p_allow_below_floor THEN
    RAISE EXCEPTION ''Listing command blocked: price decision requires override (%).'', v_snapshot.blocking_reasons;
  END IF;

  IF p_command_type = ''sync_quantity'' THEN
    IF v_listing.sku_id IS NULL THEN
      RAISE EXCEPTION ''Cannot sync quantity for listing % without sku_id'', p_channel_listing_id;
    END IF;

    SELECT COUNT(*)::integer INTO v_available_quantity
    FROM public.stock_unit su
    WHERE su.sku_id = v_listing.sku_id
      AND su.v2_status IN (''graded'', ''listed'', ''restocked'');

    v_idempotency_key :=
      p_command_type || '':channel_listing:'' || p_channel_listing_id::text || '':qty:'' || COALESCE(v_available_quantity, 0)::text;
  ELSE
    v_idempotency_key :=
      p_command_type || '':channel_listing:'' || p_channel_listing_id::text || '':'' || COALESCE(v_snapshot.id::text, ''no_snapshot'');
  END IF;

  v_target := COALESCE(v_listing.channel, v_listing.v2_channel::text, ''website'');

  INSERT INTO public.outbound_command (
    target_system,
    command_type,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    v_target,
    p_command_type,
    ''channel_listing'',
    p_channel_listing_id,
    v_idempotency_key,
    ''pending'',
    jsonb_build_object(
      ''channel_listing_id'', p_channel_listing_id,
      ''price_decision_snapshot_id'', v_snapshot.id,
      ''actor_id'', p_actor_id,
      ''listed_price'', v_listing.listed_price,
      ''listed_quantity'', COALESCE(v_available_quantity, v_listing.listed_quantity),
      ''sku_id'', v_listing.sku_id
    )
  )
  ON CONFLICT (target_system, command_type, idempotency_key) DO UPDATE
  SET status = CASE
        WHEN public.outbound_command.status IN (''failed'', ''cancelled'') THEN ''pending''
        ELSE public.outbound_command.status
      END,
      next_attempt_at = CASE
        WHEN public.outbound_command.status IN (''failed'', ''cancelled'') THEN now()
        ELSE public.outbound_command.next_attempt_at
      END,
      payload = EXCLUDED.payload,
      updated_at = now()
  RETURNING id INTO v_command_id;

  RETURN v_command_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_listing_command(UUID, TEXT, UUID, BOOLEAN)
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430230000_manage_listing_outbox_commands.sql
-- ============================================================

-- Add staff actions for retrying or cancelling listing outbox commands.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies, not dollar quotes.

CREATE OR REPLACE FUNCTION public.retry_listing_outbound_command(p_outbound_command_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_command public.outbound_command%ROWTYPE;
BEGIN
  IF NOT public.subledger_staff_read_policy() THEN
    RAISE EXCEPTION ''Not authorized to retry listing commands'';
  END IF;

  SELECT * INTO v_command
  FROM public.outbound_command
  WHERE id = p_outbound_command_id
    AND entity_type = ''channel_listing'';

  IF NOT FOUND THEN
    RAISE EXCEPTION ''Listing outbound command % not found'', p_outbound_command_id;
  END IF;

  IF v_command.status = ''processing'' THEN
    RAISE EXCEPTION ''Cannot retry listing command % while it is processing'', p_outbound_command_id;
  END IF;

  IF v_command.status IN (''acknowledged'', ''sent'') THEN
    RAISE EXCEPTION ''Cannot retry listing command % after it has been sent'', p_outbound_command_id;
  END IF;

  UPDATE public.outbound_command
  SET status = ''pending'',
      last_error = NULL,
      next_attempt_at = now(),
      updated_at = now()
  WHERE id = p_outbound_command_id;

  UPDATE public.reconciliation_case
  SET status = ''resolved'',
      close_code = ''retried_listing_command'',
      closed_at = now(),
      updated_at = now()
  WHERE case_type = ''listing_command_failed''
    AND related_entity_type = ''outbound_command''
    AND related_entity_id = p_outbound_command_id
    AND status IN (''open'', ''in_progress'');

  RETURN p_outbound_command_id;
END;
';

CREATE OR REPLACE FUNCTION public.cancel_listing_outbound_command(p_outbound_command_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_command public.outbound_command%ROWTYPE;
BEGIN
  IF NOT public.subledger_staff_read_policy() THEN
    RAISE EXCEPTION ''Not authorized to cancel listing commands'';
  END IF;

  SELECT * INTO v_command
  FROM public.outbound_command
  WHERE id = p_outbound_command_id
    AND entity_type = ''channel_listing'';

  IF NOT FOUND THEN
    RAISE EXCEPTION ''Listing outbound command % not found'', p_outbound_command_id;
  END IF;

  IF v_command.status IN (''acknowledged'', ''sent'') THEN
    RAISE EXCEPTION ''Cannot cancel listing command % after it has been sent'', p_outbound_command_id;
  END IF;

  IF v_command.status = ''processing'' THEN
    RAISE EXCEPTION ''Cannot cancel listing command % while it is processing'', p_outbound_command_id;
  END IF;

  UPDATE public.outbound_command
  SET status = ''cancelled'',
      next_attempt_at = NULL,
      updated_at = now()
  WHERE id = p_outbound_command_id;

  UPDATE public.reconciliation_case
  SET status = ''ignored'',
      close_code = ''cancelled_listing_command'',
      closed_at = now(),
      updated_at = now()
  WHERE case_type = ''listing_command_failed''
    AND related_entity_type = ''outbound_command''
    AND related_entity_id = p_outbound_command_id
    AND status IN (''open'', ''in_progress'');

  RETURN p_outbound_command_id;
END;
';

GRANT EXECUTE ON FUNCTION public.retry_listing_outbound_command(UUID)
TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.cancel_listing_outbound_command(UUID)
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430233000_record_price_override_approvals.sql
-- ============================================================

-- Record approved pricing overrides against immutable price decision snapshots.
-- Lovable SQL runner note: use single-quoted PL/pgSQL bodies, not dollar quotes.

CREATE OR REPLACE FUNCTION public.record_price_override_approval(
  p_price_decision_snapshot_id UUID,
  p_reason_code TEXT,
  p_reason_note TEXT DEFAULT NULL,
  p_approved_by UUID DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_snapshot public.price_decision_snapshot%ROWTYPE;
  v_override_id UUID;
  v_actor UUID := COALESCE(p_approved_by, auth.uid());
  v_reason_code TEXT := NULLIF(trim(COALESCE(p_reason_code, '''')), '''');
BEGIN
  IF NOT public.subledger_staff_read_policy() THEN
    RAISE EXCEPTION ''Not authorized to approve price overrides'';
  END IF;

  IF v_reason_code IS NULL THEN
    RAISE EXCEPTION ''Price override reason code is required'';
  END IF;

  SELECT * INTO v_snapshot
  FROM public.price_decision_snapshot
  WHERE id = p_price_decision_snapshot_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''Price decision snapshot % not found'', p_price_decision_snapshot_id;
  END IF;

  IF NOT COALESCE(v_snapshot.override_required, false) THEN
    RAISE EXCEPTION ''Price decision snapshot % does not require an override'', p_price_decision_snapshot_id;
  END IF;

  INSERT INTO public.price_override (
    price_decision_snapshot_id,
    sku_id,
    channel_listing_id,
    channel,
    override_type,
    old_price,
    new_price,
    reason_code,
    reason_note,
    approved_by,
    performed_by
  )
  VALUES (
    v_snapshot.id,
    v_snapshot.sku_id,
    v_snapshot.channel_listing_id,
    v_snapshot.channel,
    CASE
      WHEN COALESCE(v_snapshot.candidate_price, 0) < COALESCE(v_snapshot.floor_price, 0) THEN ''below_floor''
      ELSE ''margin_exception''
    END,
    v_snapshot.current_price,
    v_snapshot.candidate_price,
    v_reason_code,
    NULLIF(trim(COALESCE(p_reason_note, '''')), ''''),
    v_actor,
    auth.uid()
  )
  RETURNING id INTO v_override_id;

  RETURN v_override_id;
END;
';

GRANT EXECUTE ON FUNCTION public.record_price_override_approval(UUID, TEXT, TEXT, UUID)
TO authenticated, service_role;

-- ============================================================
-- Source: supabase/migrations/20260430234500_admin_subledger_maintenance_rpcs.sql
-- ============================================================

-- Admin maintenance helpers for subledger-owned allocation and SKU cost rollups.
-- Lovable SQL runner note: keep PL/pgSQL bodies single-quoted, not dollar-quoted.

CREATE OR REPLACE FUNCTION public.release_stock_allocation_for_order_line(
  p_sales_order_line_id UUID,
  p_reason TEXT DEFAULT 'admin_maintenance'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_line public.sales_order_line%ROWTYPE;
  v_stock_unit_id UUID;
  v_released INTEGER := 0;
  v_reversal_amount NUMERIC := 0;
BEGIN
  SELECT * INTO v_line
  FROM public.sales_order_line
  WHERE id = p_sales_order_line_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''sales_order_line % not found'', p_sales_order_line_id;
  END IF;

  v_stock_unit_id := v_line.stock_unit_id;
  v_reversal_amount := COALESCE(v_line.cogs_amount, v_line.cogs, 0);

  UPDATE public.stock_allocation
  SET status = ''void'',
      failure_reason = COALESCE(p_reason, ''admin_maintenance''),
      requested_stock_unit_id = CASE WHEN requested_stock_unit_id = v_stock_unit_id THEN NULL ELSE requested_stock_unit_id END,
      selected_stock_unit_id = CASE WHEN selected_stock_unit_id = v_stock_unit_id THEN NULL ELSE selected_stock_unit_id END,
      released_at = now(),
      updated_at = now()
  WHERE sales_order_line_id = p_sales_order_line_id
    AND status IN (''pending'', ''allocated'');

  GET DIAGNOSTICS v_released = ROW_COUNT;

  IF v_stock_unit_id IS NOT NULL AND v_reversal_amount <> 0 THEN
    INSERT INTO public.stock_cost_event (
      stock_unit_id,
      sales_order_id,
      sales_order_line_id,
      event_type,
      amount,
      currency,
      costing_method,
      source,
      idempotency_key,
      metadata,
      event_at
    )
    VALUES (
      v_stock_unit_id,
      v_line.sales_order_id,
      v_line.id,
      ''manual_correction'',
      -ABS(v_reversal_amount),
      ''GBP'',
      COALESCE(v_line.costing_method, ''manual_exception''),
      ''admin_maintenance_rpc'',
      ''release_cogs:'' || v_line.id::text,
      jsonb_build_object(''reason'', COALESCE(p_reason, ''admin_maintenance''), ''released_stock_unit_id'', v_stock_unit_id),
      now()
    )
    ON CONFLICT (idempotency_key) DO UPDATE
    SET amount = EXCLUDED.amount,
        metadata = EXCLUDED.metadata;
  END IF;

  UPDATE public.sales_order_line
  SET stock_unit_id = NULL,
      cogs = NULL,
      cogs_amount = NULL,
      cogs_source_unit_id = NULL,
      costing_method = ''manual_exception'',
      gross_margin_amount = NULL,
      net_margin_amount = NULL,
      net_margin_rate = NULL,
      economics_status = ''needs_allocation''
  WHERE id = p_sales_order_line_id;

  IF v_stock_unit_id IS NOT NULL THEN
    UPDATE public.stock_unit
    SET order_id = NULL,
        v2_status = CASE WHEN v2_status::text = ''sold'' THEN ''graded'' ELSE v2_status END,
        sold_at = CASE WHEN v2_status::text = ''sold'' THEN NULL ELSE sold_at END
    WHERE id = v_stock_unit_id
      AND order_id = v_line.sales_order_id;
  END IF;

  PERFORM public.refresh_order_line_economics(v_line.sales_order_id);

  RETURN jsonb_build_object(
    ''sales_order_line_id'', p_sales_order_line_id,
    ''released_stock_unit_id'', v_stock_unit_id,
    ''released_allocations'', v_released,
    ''status'', ''released''
  );
END;
';

CREATE OR REPLACE FUNCTION public.refresh_sku_cost_rollups(p_sku_id UUID DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_count INTEGER := 0;
BEGIN
  WITH target_skus AS (
    SELECT id
    FROM public.sku
    WHERE p_sku_id IS NULL OR id = p_sku_id
  ),
  stats AS (
    SELECT
      su.sku_id,
      ROUND(AVG(COALESCE(su.carrying_value, su.landed_cost)), 2) AS avg_cost,
      ROUND(MIN(COALESCE(su.carrying_value, su.landed_cost)), 2) AS min_cost,
      ROUND(MAX(COALESCE(su.carrying_value, su.landed_cost)), 2) AS max_cost
    FROM public.stock_unit su
    JOIN target_skus ts ON ts.id = su.sku_id
    WHERE COALESCE(su.carrying_value, su.landed_cost) IS NOT NULL
      AND COALESCE(su.carrying_value, su.landed_cost) > 0
      AND COALESCE(su.v2_status::text, su.status::text) IN (''graded'', ''listed'', ''available'', ''restocked'')
    GROUP BY su.sku_id
  ),
  rollups AS (
    SELECT
      ts.id AS sku_id,
      st.avg_cost,
      CASE
        WHEN st.min_cost IS NULL THEN NULL
        WHEN st.min_cost = st.max_cost THEN ''GBP '' || st.min_cost::text
        ELSE ''GBP '' || st.min_cost::text || ''-'' || st.max_cost::text
      END AS cost_range
    FROM target_skus ts
    LEFT JOIN stats st ON st.sku_id = ts.id
  )
  UPDATE public.sku sk
  SET avg_cost = rollups.avg_cost,
      cost_range = rollups.cost_range
  FROM rollups
  WHERE sk.id = rollups.sku_id;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
';

GRANT EXECUTE ON FUNCTION public.release_stock_allocation_for_order_line(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.release_stock_allocation_for_order_line(UUID, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_sku_cost_rollups(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_sku_cost_rollups(UUID) TO service_role;

COMMENT ON FUNCTION public.release_stock_allocation_for_order_line(UUID, TEXT) IS
  'Releases a sale-line stock allocation through the costing subledger and marks the line for reallocation.';
COMMENT ON FUNCTION public.refresh_sku_cost_rollups(UUID) IS
  'Refreshes deprecated SKU avg_cost/cost_range compatibility fields from saleable stock-unit carrying values.';

-- ============================================================
-- Source: supabase/migrations/20260430235500_queue_qbo_payout_posting_intents.sql
-- ============================================================

-- Queue QBO payout/deposit posting through the posting_intent outbox.
-- Lovable SQL runner note: keep PL/pgSQL bodies single-quoted, not dollar-quoted.

CREATE OR REPLACE FUNCTION public.queue_qbo_payout_posting_intent(p_payout_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_payout public.payouts%ROWTYPE;
  v_intent_id UUID;
BEGIN
  SELECT * INTO v_payout
  FROM public.payouts
  WHERE id = p_payout_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''payout % not found'', p_payout_id;
  END IF;

  IF v_payout.qbo_deposit_id IS NOT NULL
     AND COALESCE(v_payout.qbo_sync_status, '''') = ''synced'' THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.posting_intent (
    target_system,
    action,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    ''qbo'',
    ''create_payout_deposit'',
    ''payout'',
    p_payout_id,
    ''qbo:create_payout_deposit:'' || p_payout_id::text,
    ''pending'',
    jsonb_build_object(
      ''payout_id'', p_payout_id,
      ''external_payout_id'', v_payout.external_payout_id,
      ''channel'', v_payout.channel,
      ''net_amount'', v_payout.net_amount,
      ''currency'', ''GBP'',
      ''queued_at'', now()
    )
  )
  ON CONFLICT (target_system, action, idempotency_key) DO UPDATE
  SET payload = EXCLUDED.payload,
      status = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'') THEN ''pending''
        ELSE posting_intent.status
      END,
      next_attempt_at = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'') THEN now()
        ELSE posting_intent.next_attempt_at
      END,
      updated_at = now()
  RETURNING id INTO v_intent_id;

  RETURN v_intent_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_qbo_payout_posting_intent(UUID)
  TO authenticated, service_role;

COMMENT ON FUNCTION public.queue_qbo_payout_posting_intent(UUID) IS
  'Queues an idempotent QBO payout/deposit posting intent for asynchronous processing.';

-- ============================================================
-- Source: supabase/migrations/20260430235600_queue_qbo_item_posting_intents.sql
-- ============================================================

-- Queue QBO item upserts through the posting_intent outbox.
-- Lovable SQL runner note: keep PL/pgSQL bodies single-quoted, not dollar-quoted.

CREATE OR REPLACE FUNCTION public.queue_qbo_item_posting_intent(
  p_sku_id UUID,
  p_old_sku_code TEXT DEFAULT NULL,
  p_purchase_cost NUMERIC DEFAULT NULL,
  p_supplier_vat_registered BOOLEAN DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_sku public.sku%ROWTYPE;
  v_intent_id UUID;
BEGIN
  SELECT * INTO v_sku
  FROM public.sku
  WHERE id = p_sku_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''sku % not found'', p_sku_id;
  END IF;

  INSERT INTO public.posting_intent (
    target_system,
    action,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    ''qbo'',
    ''upsert_item'',
    ''sku'',
    p_sku_id,
    ''qbo:upsert_item:'' || p_sku_id::text,
    ''pending'',
    jsonb_build_object(
      ''sku_id'', p_sku_id,
      ''sku_code'', v_sku.sku_code,
      ''old_sku_code'', p_old_sku_code,
      ''purchase_cost'', p_purchase_cost,
      ''supplier_vat_registered'', p_supplier_vat_registered,
      ''queued_at'', now()
    )
  )
  ON CONFLICT (target_system, action, idempotency_key) DO UPDATE
  SET payload = EXCLUDED.payload,
      status = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN ''pending''
        ELSE posting_intent.status
      END,
      next_attempt_at = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN now()
        ELSE posting_intent.next_attempt_at
      END,
      updated_at = now()
  RETURNING id INTO v_intent_id;

  RETURN v_intent_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_qbo_item_posting_intent(UUID, TEXT, NUMERIC, BOOLEAN)
  TO authenticated, service_role;

COMMENT ON FUNCTION public.queue_qbo_item_posting_intent(UUID, TEXT, NUMERIC, BOOLEAN) IS
  'Queues an idempotent QBO Item upsert intent for asynchronous processing.';

-- ============================================================
-- Source: supabase/migrations/20260430235700_queue_qbo_customer_posting_intents.sql
-- ============================================================

-- Queue QBO customer upserts through the posting_intent outbox.
-- Lovable SQL runner note: keep PL/pgSQL bodies single-quoted, not dollar-quoted.

CREATE OR REPLACE FUNCTION public.queue_qbo_customer_posting_intent(
  p_customer_id UUID DEFAULT NULL,
  p_payload JSONB DEFAULT '{}'::jsonb
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_actor UUID := auth.uid();
  v_customer public.customer%ROWTYPE;
  v_entity_id UUID;
  v_idempotency_subject TEXT;
  v_intent_id UUID;
BEGIN
  IF p_customer_id IS NOT NULL THEN
    SELECT * INTO v_customer
    FROM public.customer
    WHERE id = p_customer_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION ''customer % not found'', p_customer_id;
    END IF;

    v_entity_id := p_customer_id;
    v_idempotency_subject := p_customer_id::text;
  ELSE
    v_idempotency_subject := COALESCE(v_actor::text, p_payload->>''email'', gen_random_uuid()::text);
  END IF;

  INSERT INTO public.posting_intent (
    target_system,
    action,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    ''qbo'',
    ''upsert_customer'',
    ''customer'',
    v_entity_id,
    ''qbo:upsert_customer:'' || v_idempotency_subject,
    ''pending'',
    COALESCE(p_payload, ''{}''::jsonb)
      || jsonb_build_object(
        ''customer_id'', p_customer_id,
        ''queued_by'', v_actor,
        ''queued_at'', now()
      )
  )
  ON CONFLICT (target_system, action, idempotency_key) DO UPDATE
  SET payload = EXCLUDED.payload,
      entity_id = COALESCE(EXCLUDED.entity_id, posting_intent.entity_id),
      status = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN ''pending''
        ELSE posting_intent.status
      END,
      next_attempt_at = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN now()
        ELSE posting_intent.next_attempt_at
      END,
      updated_at = now()
  RETURNING id INTO v_intent_id;

  RETURN v_intent_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_qbo_customer_posting_intent(UUID, JSONB)
  TO authenticated, service_role;

COMMENT ON FUNCTION public.queue_qbo_customer_posting_intent(UUID, JSONB) IS
  'Queues an idempotent QBO Customer upsert intent for asynchronous processing.';

-- ============================================================
-- Source: supabase/migrations/20260430235800_queue_qbo_purchase_posting_intents.sql
-- ============================================================

-- Queue QBO purchase create/update/delete through the posting_intent outbox.
-- Lovable SQL runner note: keep PL/pgSQL bodies single-quoted, not dollar-quoted.

CREATE OR REPLACE FUNCTION public.queue_qbo_purchase_posting_intent(
  p_batch_id UUID,
  p_action TEXT DEFAULT 'create_purchase'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS '
DECLARE
  v_batch public.purchase_batches%ROWTYPE;
  v_action TEXT := COALESCE(NULLIF(trim(p_action), ''''), ''create_purchase'');
  v_intent_id UUID;
BEGIN
  IF v_action NOT IN (''create_purchase'', ''update_purchase'', ''delete_purchase'') THEN
    RAISE EXCEPTION ''unsupported QBO purchase action %'', v_action;
  END IF;

  SELECT * INTO v_batch
  FROM public.purchase_batches
  WHERE id = p_batch_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION ''purchase batch % not found'', p_batch_id;
  END IF;

  IF v_action = ''create_purchase''
     AND v_batch.qbo_purchase_id IS NOT NULL
     AND COALESCE(v_batch.qbo_sync_status, '''') = ''synced'' THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.posting_intent (
    target_system,
    action,
    entity_type,
    entity_id,
    idempotency_key,
    status,
    payload
  )
  VALUES (
    ''qbo'',
    v_action,
    ''purchase_batch'',
    p_batch_id,
    ''qbo:'' || v_action || '':'' || p_batch_id::text,
    ''pending'',
    jsonb_build_object(
      ''batch_id'', p_batch_id,
      ''purchase_batch_id'', p_batch_id,
      ''reference'', v_batch.reference,
      ''supplier_name'', v_batch.supplier_name,
      ''qbo_purchase_id'', v_batch.qbo_purchase_id,
      ''queued_at'', now()
    )
  )
  ON CONFLICT (target_system, action, idempotency_key) DO UPDATE
  SET payload = EXCLUDED.payload,
      status = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN ''pending''
        ELSE posting_intent.status
      END,
      next_attempt_at = CASE
        WHEN posting_intent.status IN (''failed'', ''cancelled'', ''posted'') THEN now()
        ELSE posting_intent.next_attempt_at
      END,
      updated_at = now()
  RETURNING id INTO v_intent_id;

  RETURN v_intent_id;
END;
';

GRANT EXECUTE ON FUNCTION public.queue_qbo_purchase_posting_intent(UUID, TEXT)
  TO authenticated, service_role;

COMMENT ON FUNCTION public.queue_qbo_purchase_posting_intent(UUID, TEXT) IS
  'Queues an idempotent QBO Purchase posting intent for purchase batch create/update/delete processing.';
