INSERT INTO public.canonical_attribute
  (key, label, attribute_group, editor, data_type, unit, db_column, provider_chain, editable, sort_order, active)
VALUES
  -- Identity
  ('brand', 'Brand', 'identity', 'text', 'string', NULL, NULL,
   '[{"provider":"constant","field":"LEGO"}]'::jsonb, false, 10, true),
  ('mpn', 'MPN', 'identity', 'text', 'string', NULL, 'mpn',
   '[{"provider":"product","field":"mpn"}]'::jsonb, false, 20, true),
  ('set_number', 'Set Number', 'identity', 'text', 'string', NULL, 'mpn',
   '[{"provider":"product","field":"mpn"},{"provider":"derived","field":"set_number_from_mpn"}]'::jsonb,
   false, 30, true),
  ('product_name', 'Product Name', 'identity', 'text', 'string', NULL, 'name',
   '[{"provider":"product","field":"name"},{"provider":"catalog","field":"name"},{"provider":"brickeconomy","field":"name"}]'::jsonb,
   true, 40, true),
  ('theme', 'Theme', 'identity', 'text', 'string', NULL, NULL,
   '[{"provider":"theme","field":"name"},{"provider":"catalog","field":"theme_name"},{"provider":"brickeconomy","field":"theme"}]'::jsonb,
   true, 50, true),
  ('subtheme', 'Subtheme', 'identity', 'text', 'string', NULL, 'subtheme_name',
   '[{"provider":"product","field":"subtheme_name"},{"provider":"catalog","field":"subtheme_name"},{"provider":"brickeconomy","field":"subtheme"}]'::jsonb,
   true, 60, true),

  -- Physical
  ('piece_count', 'Piece Count', 'physical', 'number', 'int', 'pieces', 'piece_count',
   '[{"provider":"product","field":"piece_count"},{"provider":"catalog","field":"piece_count"},{"provider":"brickeconomy","field":"pieces_count"}]'::jsonb,
   true, 110, true),
  ('minifig_count', 'Minifigure Count', 'physical', 'number', 'int', 'minifigs', NULL,
   '[{"provider":"brickeconomy","field":"minifigs_count"},{"provider":"catalog","field":"minifig_count"}]'::jsonb,
   true, 120, true),
  ('weight_grams', 'Weight', 'physical', 'number', 'int', 'g', NULL,
   '[{"provider":"product","field":"weight_grams"},{"provider":"catalog","field":"weight_grams"}]'::jsonb,
   true, 130, true),
  ('length_mm', 'Length', 'physical', 'number', 'int', 'mm', NULL,
   '[{"provider":"product","field":"length_mm"}]'::jsonb, true, 140, true),
  ('width_mm', 'Width', 'physical', 'number', 'int', 'mm', NULL,
   '[{"provider":"product","field":"width_mm"}]'::jsonb, true, 150, true),
  ('height_mm', 'Height', 'physical', 'number', 'int', 'mm', NULL,
   '[{"provider":"product","field":"height_mm"}]'::jsonb, true, 160, true),

  -- Marketing
  ('condition', 'Condition', 'marketing', 'select', 'string', NULL, NULL,
   '[{"provider":"derived","field":"condition_from_grade"}]'::jsonb,
   false, 210, true),
  ('age_range', 'Recommended Age', 'marketing', 'text', 'string', NULL, NULL,
   '[{"provider":"product","field":"age_range"},{"provider":"catalog","field":"age_range"}]'::jsonb,
   true, 220, true),
  ('packaging', 'Packaging', 'marketing', 'select', 'string', NULL, NULL,
   '[{"provider":"constant","field":"Box"}]'::jsonb,
   true, 230, true),

  -- Lifecycle
  ('release_year', 'Release Year', 'lifecycle', 'number', 'int', NULL, 'release_year',
   '[{"provider":"product","field":"release_year"},{"provider":"catalog","field":"release_year"},{"provider":"brickeconomy","field":"year"}]'::jsonb,
   true, 310, true),
  ('retired_flag', 'Retired', 'lifecycle', 'select', 'bool', NULL, 'retired_flag',
   '[{"provider":"product","field":"retired_flag"},{"provider":"catalog","field":"retired_flag"}]'::jsonb,
   true, 320, true),
  ('version_descriptor', 'Version', 'lifecycle', 'text', 'string', NULL, 'version_descriptor',
   '[{"provider":"product","field":"version_descriptor"},{"provider":"catalog","field":"version_descriptor"}]'::jsonb,
   true, 330, true),
  ('product_type', 'Product Type', 'lifecycle', 'select', 'string', NULL, 'product_type',
   '[{"provider":"product","field":"product_type"}]'::jsonb,
   false, 340, true)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  attribute_group = EXCLUDED.attribute_group,
  editor = EXCLUDED.editor,
  data_type = EXCLUDED.data_type,
  unit = EXCLUDED.unit,
  db_column = EXCLUDED.db_column,
  provider_chain = EXCLUDED.provider_chain,
  editable = EXCLUDED.editable,
  sort_order = EXCLUDED.sort_order,
  active = EXCLUDED.active,
  updated_at = now();